sudo: false
os:
  - linux

language: python
python:
  - "2.7"
  - "3.6"
  
before_install:
  - sudo apt-get update
  - sudo apt-get install -y wkhtmltopdf
  - sudo apt-get install -y xvfb
  
install:
  - python3 -m pip install -r python/requirements.txt
  
# elf_diff uses the pdfkit python package which uses wkhtmltopdf
# under the hood which needs an x-server.
#
script: 
  - xvfb-run -a -s "-screen 0 640x480x16" python3 testing/test.py
  - python3 testing/test_cpp_symbols.py
  
notifications:
  email:
    recipients:
      - shinynoseglasses@gmail.com
    on_failure: always
