# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format_checking:
    name: Check Python Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Ubuntu packages
      run: |
         sudo apt install -y python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
         #sudo apt install -y w3c-linkchecker 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest weasyprint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # E203: Spaces around colons in array indexing collides with black-formatting
        # E402: Imports always on top collide with the need to set the python module search path in some places
        # W503: Collides with black formatting
        flake8 . --count --max-complexity=10 --max-line-length=200 --statistics --ignore=E203,E402,W503
    - name: Test
      run: |
        mkdir test_output
        cd test_output
        python3 ../tests/test.py
        python3 ../tests/test_cpp_symbols.py
    - name: HTML check
      run: |
        pwd
        cd test_output
        tree
        cd /home/runner/work/elf_diff/elf_diff/test_output
        tree
    - name: HTML Link Check
      uses: lycheeverse/lychee-action@v1.0.8
      id: lychee_html
      with:
        args: --verbose --no-progress "/github/workspace/test_output/**/*.html"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Fail on HTML Link Check Errors
      run: exit ${{ steps.lychee_html.outputs.exit_code }}
    - name: Python Packaging
      run: |
        python3 -m pip install build
        python -m build
    - name: Prepare Example Deploy
      run: |
        mkdir example_deploy
        cd example_deploy
        cp -a ../test_output/pair_report_multi_page .
        cp ../test_output/pair_report_output.html .
        cp ../html/example_page.html ./index.html
    - name: Deploy To Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: ${{ github.event_name == 'push' }} # Only run on push to master (which only happens if a PR is merged)
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: /home/runner/work/elf_diff/elf_diff/example_deploy # The folder the action should deploy.
    - name: README.md Link Check
      uses: lycheeverse/lychee-action@v1.0.8
      id: lychee_readme_md
      with:
        args: --verbose --no-progress "/github/workspace/README.md"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Fail on README.md Link Check Errors
      run: exit ${{ steps.lychee_readme_md.outputs.exit_code }}
