name: Module Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  module_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Ubuntu packages
      run: |
         sudo apt install -y python3-pip
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest
        python3 -m pip install -r ./requirements.txt
    - name: Test
      run: |
        mkdir test_output
        cd test_output
        python3 ../tests/test.py
        python3 ../tests/test_cpp_symbols.py
    - name: Prepare Example Deploy
      run: |
        mkdir example_deploy
        cd example_deploy
        cp -a ../test_output/pair_report_multi_page .
        cp ../test_output/pair_report_output.html .
        cp ../src/elf_diff/html/example_page.html ./index.html
    - name: Deploy To Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: ${{ github.event_name == 'push' }} # Only run on push to master (which only happens if a PR is merged)
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: /home/runner/work/elf_diff/elf_diff/example_deploy # The folder the action should deploy.
